#!/usr/bin/env python3
"""Turn media-2026/manifest.csv (from the archive survey) into lib/gallery.ts.

Usage: python3 scripts/gallery-manifest.py path/to/manifest.csv > lib/gallery.ts

Rows flagged faces=faces (an identifiable young man) are left out of the site
until the Society has a release for them; they stay in the drive folder.
"""
import csv, sys, json

YEAR = {"y2024": 2024, "y2019": 2019, "y2022": 2022, "y2016": 2016, "y2006": 2006, "y2007": 2007, "ymawphotos": 0,
        "JACOB YMAW EDITS": 2023, "2019 media": 2019, "2022 media": 2022, "ymaw2023": 2023, "2024 camp videos": 2024,
        "inc photos 2024": 2024, "YMAW 2016 Imagery": 2016, "ymaw 2013 video": 2013}
EXCLUDE = {"faces"}

rows = list(csv.DictReader(open(sys.argv[1], encoding="utf-8")))
items = []
for r in rows:
    if not r["file"] or r["file"].startswith("ERR") or r["src"] == "MISSING":
        continue
    if r["faces"] in EXCLUDE:
        continue
    key = r["set"]
    year = YEAR.get(key)
    if year is None:
        for k, v in YEAR.items():
            if k in (r.get("src") or ""):
                year = v; break
    if year is None:
        year = 0
    w, h = int(r["w"] or 0), int(r["h"] or 0)
    it = {"id": r["id"], "kind": r["kind"], "src": "/media/gallery/" + r["file"], "w": w, "h": h,
          "stage": r["stage"], "year": year, "note": r["note"].replace(" vertical", "").strip(), "faces": r["faces"]}
    if r["kind"] == "still":
        it["small"] = "/media/gallery/" + r["poster"]
    else:
        it["poster"] = "/media/gallery/" + r["poster"]
        it["dur"] = float(r["dur"] or 0)
    items.append(it)

# order: mix film and stills by chapter order, newest first inside a chapter
ORDER = ["ordinary", "call", "threshold", "allies", "camp", "trials", "ordeal", "reward", "roadback", "return", "men"]
items.sort(key=lambda i: (ORDER.index(i["stage"]) if i["stage"] in ORDER else 99, -i["year"], i["id"]))

print("// Generated by scripts/gallery-manifest.py from media-2026/manifest.csv. Do not edit by hand.")
print("// Every item is a real frame from a YMAW weekend. `faces` says how identifiable the young men are.")
print("export type GalleryItem = {")
print("  id: string; kind: \"still\" | \"clip\"; src: string; small?: string; poster?: string; dur?: number;")
print("  w: number; h: number; stage: string; year: number; note: string; faces: string;")
print("};")
print("export const GALLERY: GalleryItem[] = " + json.dumps(items, ensure_ascii=False, indent=1) + ";")
print("export const GALLERY_YEARS = " + json.dumps(sorted({i['year'] for i in items})) + ";")
